# Generated by Django 3.2.8 on 2022-02-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_alter_rentin_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentin',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rentin',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='rentin',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
