# Generated by Django 3.2.8 on 2022-02-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20220209_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentin',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
