# Generated by Django 3.2.8 on 2022-02-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_alter_rentin_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentin',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
