# Generated by Django 3.2.8 on 2022-02-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_alter_rentin_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentin',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='photo/'),
        ),
    ]
