# Generated by Django 3.2.8 on 2022-03-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0013_alter_rentin_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/images/'),
        ),
    ]
