# Generated by Django 3.2.8 on 2022-03-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0014_alter_rentin_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentin',
            name='image',
            field=models.ImageField(default='product/images/default.jpg', upload_to='product/images/'),
        ),
    ]
