# Generated by Django 3.2.8 on 2022-03-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile/profile_pics/default.jpg', upload_to='profile/profile_pics'),
        ),
    ]
